# Generated by Django 3.2 on 2024-05-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20240503_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='genre',
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='title', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
