# Generated by Django 3.2 on 2024-05-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240503_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, related_name='titles', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
