# Generated by Django 3.2 on 2024-05-12 06:49

import django.core.validators
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20240512_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-1000), django.core.validators.MaxValueValidator(reviews.models.get_current_year)], verbose_name='Год выпуска'),
        ),
    ]
