# Generated by Django 3.2 on 2024-05-07 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ['name'], 'verbose_name': 'произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
