# Generated by Django 3.2 on 2024-05-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20240507_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['review'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['title'], 'verbose_name': 'отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
